FROM ubuntu:24.04

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y curl gpg \
    && install -dm 755 /etc/apt/keyrings \
    && curl -fsSL https://mise.jdx.dev/gpg-key.pub | gpg --dearmor -o /etc/apt/keyrings/mise-archive-keyring.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=amd64] https://mise.jdx.dev/deb stable main" | tee /etc/apt/sources.list.d/mise.list \
    && apt-get update \
    && apt-get install -y mise git gcc libatomic1 python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# GCC and libatomic required for markdownlint_cli installation

RUN git config --global --add safe.directory '*'

# git config --global --add safe.directory '/repo'
