---
name: "Deploy Terragrunt Module"
description: "Configure AWS credentials, install mise, and run Terragrunt init/plan/apply"

inputs:
  aws_role_arn:
    description: "AWS IAM Role ARN for OIDC authentication"
    required: true
  aws_region:
    description: "AWS Region"
    required: false
    default: "eu-west-2"
  working_directory:
    description: "Working directory containing the Terragrunt configuration"
    required: true
  action:
    description: "Terragrunt action: plan, apply, destroy-plan, destroy"
    required: false
    default: "apply"
  lock_enabled:
    description: "Whether to enable state locking (default: true)"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_role_arn }}
        aws-region: ${{ inputs.aws_region }}

    - name: Install mise tools
      uses: ./hometest-mgmt-terraform/.github/actions/install-mise
      with:
        working_directory: ${{ inputs.working_directory }}

    - name: Cache terraform providers
      uses: actions/cache@v5
      with:
        path: |
          ~/.cache/terraform
          .terraform-plugin-cache
        key: terraform-${{ runner.os }}-${{ hashFiles('**/providers.tf') }}
        restore-keys: |
          terraform-${{ runner.os }}-mgmt-

    - name: Terragrunt Init
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: mise exec -- terragrunt init

    - name: Terragrunt Plan
      if: inputs.action == 'plan' || inputs.action == 'apply'
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: mise exec -- terragrunt plan -out=tfplan ${{ inputs.lock_enabled == 'false' && '-lock=false' || '' }}

    - name: Terragrunt Destroy Plan
      if: inputs.action == 'destroy-plan' || inputs.action == 'destroy'
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: mise exec -- terragrunt plan -destroy -out=tfplan

    - name: Terragrunt Apply
      if: inputs.action == 'apply' || inputs.action == 'destroy'
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: mise exec -- terragrunt apply -auto-approve tfplan
