---
name: "Deploy Terragrunt Module"
description: "Configure AWS credentials, install mise, and run Terragrunt init/plan/apply"

inputs:
  aws_role_arn:
    description: "AWS IAM Role ARN for OIDC authentication"
    required: true
  aws_region:
    description: "AWS Region"
    required: false
    default: "eu-west-2"
  working_directory:
    description: "Working directory containing the Terragrunt configuration"
    required: true
  action:
    description: "Terragrunt action: plan, apply, destroy-plan, destroy"
    required: false
    default: "apply"
  lock_enabled:
    description: "Whether to enable state locking (default: true)"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_role_arn }}
        aws-region: ${{ inputs.aws_region }}

    - name: test
      shell: bash
      run: |
        echo "Working dir: $(pwd)"
        echo
        echo "Listing current directory:"
        ls
        echo
        echo "Contents of hometest-mgmt-terraform:"
        ls hometest-mgmt-terraform/
        echo
        echo "Contents of hometest-service:"
        ls hometest-service/
        echo
        echo "Listing ../"
        ls ../
        echo
        echo "Listing ../../"
        ls ../../

        echo
        ls -l "/home/runner/work/hometest-mgmt-terraform/hometest-mgmt-terraform/.github/actions"

    - name: Install mise tools
      uses: NHSDigital/hometest-mgmt-terraform/.github/actions/install-mise@main

    - name: Terragrunt Init
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: mise exec -- terragrunt init

    - name: Terragrunt Plan
      if: inputs.action == 'plan' || inputs.action == 'apply'
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: mise exec -- terragrunt plan -out=tfplan ${{ inputs.lock_enabled == 'false' && '-lock=false' || '' }}

    - name: Terragrunt Destroy Plan
      if: inputs.action == 'destroy-plan' || inputs.action == 'destroy'
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: mise exec -- terragrunt plan -destroy -out=tfplan

    - name: Terragrunt Apply
      if: inputs.action == 'apply' || inputs.action == 'destroy'
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: mise exec -- terragrunt apply -auto-approve tfplan
