---
name: "Perform pre-commit checks"
description: "Perform pre-commit checks"
runs:
  using: "composite"
  steps:
    - name: Cache pre-commit hooks
      uses: actions/cache@v5
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          pre-commit-${{ runner.os }}-mgmt-

    - name: Install pre-commit hooks
      shell: bash
      run: |
        echo "::group::Install pre-commit hooks"
        mise exec -- pre-commit install --install-hooks
        echo "::endgroup::"

    - name: Run pre-commit
      shell: bash
      run: |
        echo "::group::Run pre-commit checks"
        mise exec -- pre-commit run --all-files --show-diff-on-failure --color=always
        echo "::endgroup::"
      env:
        PRE_COMMIT_COLOR: always
