---
name: "Perform pre-commit checks"
description: "Perform pre-commit checks"
inputs:
  terraform_docs_version:
    description: "Version of terraform-docs to install"
    required: true
    default: "0.21.0"
runs:
  using: "composite"
  steps:
    - name: Install pre-commit dependencies
      working-directory: /tmp
      shell: bash
      run: |
        echo "Install terraform_docs ${{ inputs.terraform_docs_version }}"
        curl -sL https://github.com/terraform-docs/terraform-docs/releases/download/v${{ inputs.terraform_docs_version }}/terraform-docs-v${{ inputs.terraform_docs_version }}-linux-amd64.tar.gz -O
        tar -xf terraform-docs-v${{ inputs.terraform_docs_version }}-linux-amd64.tar.gz -C /tmp
        sudo mv /tmp/terraform-docs /usr/bin/
        rm -rf terraform-docs-v${{ inputs.terraform_docs_version }}-linux-amd64.tar.gz
        terraform-docs --version

        echo "Install pipx checkov"
        sudo pipx install --global checkov
        checkov --version

    - name: Install pre-commit
      shell: bash
      run: |
        # whereis pre-commit
        # pre-commit
        sudo pipx install --global pre-commit
        git config --global --add safe.directory '*'
        pre-commit install --install-hooks

    - name: Run pre-commit
      shell: bash
      run: |
        pre-commit run --all-files --show-diff-on-failure --color=always
      env:
        PRE_COMMIT_COLOR: always
