---
name: "Install mise"
description: "Install mise and repo dependencies"
runs:
  using: "composite"
  steps:
    - name: Configure git
      shell: bash
      run: |
        echo "::group::Configure git"
        git config --global --add safe.directory '*'
        echo "::endgroup::"

    - name: Install mise
      uses: jdx/mise-action@v3
      with:
        cache: true
        install: true
        cache_key_prefix: mise-${{ runner.os }}-mgmt-
