---
name: "Install mise"
description: "Install mise and repo dependencies"
inputs:
  working_directory:
    description: "Directory containing the .tool-versions file"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Configure git
      shell: bash
      run: |
        echo "::group::Configure git"
        git config --global --add safe.directory '*'
        echo "::endgroup::"

    - name: Cache mise
      uses: actions/cache@v5
      with:
        path: |
          ~/.local/share/mise
          ${{ inputs.working_directory }}/.mise-cache
        key: mise-${{ runner.os }}-mgmt-${{ github.event_name == 'pull_request' && 'pr' || 'push' }}-${{ hashFiles(format('{0}/.mise.toml', inputs.working_directory)) }}
        restore-keys: |
          mise-${{ runner.os }}-mgmt-${{ github.event_name == 'pull_request' && 'pr' || 'push' }}-
          mise-${{ runner.os }}-mgmt-
          mise-${{ runner.os }}-

    - name: Install mise
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        curl https://mise.run | sh
        echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
        echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH

    - name: Mise install
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        mise install
