# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "nhs-hometest-poc-core-s3-tfstate"
    encrypt      = true
    key          = "nhs-hometest-poc-dev-mikmio-dev-mikmio.tfstate"
    kms_key_id   = "arn:aws:kms:eu-west-2:781863586270:key/3e87d63f-febc-4dd4-a771-92c3c07a51f5"
    region       = "eu-west-2"
    use_lockfile = true
  }
}
